
table.insert(christmas.loot, { name="default:gold_lump", count=10 })
table.insert(christmas.loot, { name="default:coal_lump", count=25 })
table.insert(christmas.loot, { name="default:copper_lump", count=40 })
table.insert(christmas.loot, { name="default:clay_lump", count=50 })
table.insert(christmas.loot, { name="default:iron_lump", count=30 })
table.insert(christmas.loot, { name="default:tin_lump", count=40 })
table.insert(christmas.loot, { name="default:gold_ingot", count=10 })
table.insert(christmas.loot, { name="default:goldblock", count=4 })
table.insert(christmas.loot, { name="default:diamondblock", count=2 })
table.insert(christmas.loot, { name="default:diamond", count=5 })
table.insert(christmas.loot, { name="default:mese", count=2 })
table.insert(christmas.loot, { name="default:mese_crystal", count=5 })
table.insert(christmas.loot, { name="default:mese_crystal_fragment", count=15 })
